### PR TITLE
modified visbrain fig

### PR DESCRIPTION
**Pull request by annapasca**

### CODE REVIEW

**Comment by annapasca** [comment]
Hi @jasmainak , I got this message
` Failed to fetch http://security.debian.org/debian-security/pool/updates/main/c/cups/libcups2_1.7.5-11+deb8u4_amd64.deb  404  Not Found`

Where do I have to modify to fix this circleCi problem? thks a lot!

**Comment by annapasca** [comment]
> Hi @jasmainak , I got this message
> ` Failed to fetch http://security.debian.org/debian-security/pool/updates/main/c/cups/libcups2_1.7.5-11+deb8u4_amd64.deb 404 Not Found`
> 
> Where do I have to modify to fix this circleCi problem? thks a lot!

@jasmainak  I fixed it :)

**Comment by jasmainak** [comment]
wow excellent 

good to know that just tagging me fixes your problem ;)

**Comment by annapasca** [comment]
> wow excellent
> 
> good to know that just tagging me fixes your problem ;)

yes, it's true!!! :)

**Pull request merged**
