### PR TITLE
Merge import data

### PR DESCRIPTION
**Pull request by davidmeunier79**

### CODE REVIEW

**Comment by annapasca** [comment]
[here](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L99) is `orig_channel_names_file` or `orig_channel_coords_file`?
the same [here](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L107)

[this](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L108) is a bug, the right code, as you wrote in [_import_tsmat_to_ts](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L161) is

`        correct_channel_names = [line.strip() for line in
                                 open(orig_channel_names_file)]`

**Comment by davidmeunier79** [comment]
> [here](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L99) is `orig_channel_names_file` or `orig_channel_coords_file`?
> the same [here](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L107)
> 
> [this](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L108) is a bug, the right code, as you wrote in [_import_tsmat_to_ts](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L161) is
> 
> ` correct_channel_names = [line.strip() for line in open(orig_channel_names_file)]`

Yes that's right, I have modified it

**Comment by annapasca** [comment]
> > [here](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L99) is `orig_channel_names_file` or `orig_channel_coords_file`?
> > the same [here](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L107)
> > [this](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L108) is a bug, the right code, as you wrote in [_import_tsmat_to_ts](https://github.com/neuropycon/ephypype/blob/dd0b7bd0805633abda516df8749ef01db0b497ab/ephypype/import_data.py#L161) is
> > ` correct_channel_names = [line.strip() for line in open(orig_channel_names_file)]`
> 
> Yes that's right, I have modified it

great! :)

**Comment by annapasca** [comment]
thks  @davidmeunier79 !

**Pull request merged**
