### PR TITLE
[MRG] Fix allow pickle

### PR DESCRIPTION
**Pull request by davidmeunier79**
Error in Victor's code, seems to be related to newest version of numpy

### CODE REVIEW

**Comment by davidmeunier79** [comment]
@EtienneCmb I do not understand where the error comes from, seems related to the generation of the Figures with visbrain in the doc??? I did not touch this part at all

**Comment by EtienneCmb** [comment]
@davidmeunier79 does the `plot_power.py` works locally?

**Comment by EtienneCmb** [comment]
it seems that there's an error for the sources' coordinates

**Comment by annapasca** [comment]
@EtienneCmb @davidmeunier79 I had the same error with the PR #91 
To understand the problem I changed line 174 from this code
`s_obj = SourceObj('s', xyz, data=psd, radius_min=rx[0], radius_max=rx[1])`
to this
`s_obj = SourceObj('s', xyz, data=psd)`
and it works...but I don't understand the problem o.O

**Comment by EtienneCmb** [comment]
the test in the `SourceObj` is `assert sh[1] in [2, 3]`, which means that the coordinates of the sources should either be (n_sources, 2) or (n_sources, 3). There's no reason that removing `radius_min` and `radius_max` fix the issue.

How are the coordinates loaded? Is it in a hdf5 / npy file? You should print the shape of the sources both locally and on travis / circle to see if there's a difference

**Comment by EtienneCmb** [comment]
Maybe a dependency has been updated on travis / circle and the shape of your array changed?

**Comment by annapasca** [comment]
> @davidmeunier79 does the `plot_power.py` works locally?

yes, locally it works

**Comment by annapasca** [comment]
@davidmeunier79 @EtienneCmb I think it was a problem related to the way I grab the channel file.
Thks @EtienneCmb !
I fixed here https://github.com/neuropycon/ephypype/blob/e1bb411764e12e98b61ad63e93b819a7620d1d17/ephypype/gather/gather_results.py#L64

**Comment by EtienneCmb** [comment]
Well done ! @annapasca miss u in Marseille :D

**Comment by annapasca** [comment]
> Well done ! @annapasca miss u in Marseille :D

I'll come back :D

**Comment by annapasca** [comment]
@davidmeunier79 Dima merged #91 thus now probably the problem you had is fixed

**Comment by NealWood** [comment]
Hello!
&nbsp; &nbsp; &nbsp;I'm Nealwood, it seems that somebody added me to your Github project by mistake, and since yesterday I could recieve your e-mails......
&nbsp; &nbsp; &nbsp;Maybe you could check up your project members in case that somebody else was added wrongly.
&nbsp; &nbsp; &nbsp;Thanks!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Annalisa Pascarella"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 下午4:36
收件人:&nbsp;"neuropycon/ephypype"<ephypype@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [neuropycon/ephypype] Fix allow pickle (#92)




@davidmeunier79 Dima merged #91 thus now probably the problem you had is fixed

**Comment by annapasca** [comment]
@davidmeunier79 ok the issue was fixed. If it's ok I can merge it.

**Comment by davidmeunier79** [comment]
Nice! After the merge with Dima's PR, it seems to be. Many thanks to you!

**Pull request merged**
