### PR TITLE
included cli doc

### PR DESCRIPTION
**Pull request by annapasca**
Added cli doc into ephypype doc

### CODE REVIEW

**Comment by dmalt** [comment]
Thanks! Looks good!

**Comment by jasmainak** [comment]
can you reduce the size of the png?

and when merging, do a "squash and merge"

**Comment by annapasca** [comment]
> can you reduce the size of the png?
> 
> and when merging, do a "squash and merge"

done!

**Comment by jasmainak** [comment]
did you change the size? :) I see it's still 117 KB.

**Comment by annapasca** [comment]
> did you change the size? :) I see it's still 117 KB.

yes...I pushed the new png o.O

**Comment by annapasca** [comment]
@dmalt could you squash and merge? thks! :)

**Comment by dmalt** [comment]
done!

**Comment by annapasca** [comment]
> done!

Grazie!!! :)

**Pull request merged**
