### PR TITLE
remove appveyor config

### PR DESCRIPTION
**Pull request by dmalt**

### CODE REVIEW

**Comment by jasmainak** [comment]
okay let me merge this. I disabled it from my account but I am not 100% sure it worked. If it doesn't, then the person who enabled it might have to do it. It's probably @EtienneCmb

**Comment by dmalt** [comment]
Did you remove the appveyor webhook? I still can see it in settings.

**Comment by jasmainak** [comment]
okay perfect!

Thanks a ton

**Comment by jasmainak** [comment]
@dmalt we forgot to remove the appveyor badge from the readme

**Comment by dmalt** [comment]
Yes, sorry. I'll create another PR

**Pull request merged**
