### PR TITLE
Add appveyor and codecov badge

### PR DESCRIPTION
**Pull request by jasmainak**

### CODE REVIEW

**Comment by jasmainak** [comment]
@EtienneCmb merge if you are happy

**Comment by EtienneCmb** [comment]
I'm always happy

**Comment by jasmainak** [comment]
I'm just following the policy of not merging my own PR :)

**Comment by jasmainak** [comment]
> I'm always happy

:rofl:

**Comment by jasmainak** [comment]
@EtienneCmb did you do a squash and merge? It's a good practice for big repos like scikit-learn. But if we do it now, it will be hard to roll back changes if needed.

**Comment by EtienneCmb** [comment]
@jasmainak yes I do squash and merge and ok, I will not do squash and merge again :)

**Pull request merged**
