### PR TITLE
wrong default argument in create_pipeline_source_reconstruction

### PR DESCRIPTION
**Pull request by hyruuk**
events_id=None led to the following error message when is_epoched=True : 

```Traceback (most recent call last):
  File "saflow_inverse.py", line 67, in <module>
    noise_cov_fname=noise_cov_fname, is_epoched=True, events_id=None)
  File "/home/karim/anaconda3/envs/neuropycon/lib/python3.7/site-packages/ephypype-0.2-py3.7.egg/ephypype/pipelines/fif_to_inv_sol.py", line 116, in create_pipeline_source_reconstruction
    define_epochs.inputs.events_id = events_id
  File "/home/karim/anaconda3/envs/neuropycon/lib/python3.7/site-packages/traits/trait_types.py", line 2627, in validate
    self.error( object, name, value )
  File "/home/karim/anaconda3/envs/neuropycon/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'events_id' trait of a DefineEpochsInputSpec instance must be a dictionary with keys which are any value and with values which are any value, but a value of None <class 'NoneType'> was specified.```

### CODE REVIEW

**Comment by jasmainak** [comment]
what version of MNE are you using? @annapasca what is your opinion on this PR?

**Comment by hyruuk** [comment]
I'm using the version 0.20.5 of MNE

**Comment by annapasca** [comment]
@jasmainak @hyruuk hi all! I have also seen there is this little bug. Thanks @hyruuk to fix it!

**Comment by annapasca** [comment]
I'll check for the travis error

**Comment by jasmainak** [comment]
thank you!

**Comment by annapasca** [comment]
fixed in #110 
Thanks @hyruuk !!!

**Pull request closed without merging**
