### PR TITLE
PEP8 style fixes 

### PR DESCRIPTION
**Pull request by dmalt**
- Automatic pep8 style fixes for the whole project (minor fixes such as missing and trailing whitespaces
  and too long lines)
- Manual style fixes in ephypype/interfaces/mne/spectral.py and ephypype/spectral.py.
  Fix two things pep8 style checker was unhappy about:
  1. conmat_file (and some others) defined outside __init__  method in interface classes.
      Fix - create `__init__` method and initialize corresponding variables
  2. too many local variables in `PlotSpectralConn._run_interface`.
      Fix - remove some temp variables and use `self.inputs.<varname>` instead.
      Number  of local variables is still over limit, so it's worth consider rewriting `_run_interface`
      method for better readability.

- fix issue with obsolete `add_eeg_ref` argument to `Epochs` call in `preproc.create_epochs` function

### CODE REVIEW

**Comment by annapasca** [comment]
For me it's ok. For you @davidmeunier79 ?

**Comment by davidmeunier79** [comment]
Yes after checking it seems a good thing you did that, Dima! Many thanks!

**Comment by davidmeunier79** [comment]
sorry I thought it would merge automatically if I closed the pull request!

**Comment by dmalt** [comment]
Thanks for checking!
Also I'm finishing docs for CLI.
Will merge soon.
And Happy New Year)

**Comment by annapasca** [comment]
Great! happy new year to both of you! :)

**Pull request merged**
